---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 24/01/2023 23:42
---

TickManager = {};

function TickManager:init()
    self.ticks = {};
end

function TickManager:addTick(name,func)
    self.ticks[name] = func;
end

function TickManager:removeTick(name)
    if self.ticks[name] then
        self.ticks[name] = nil;
    end
end

function TickManager:analayze()
    Citizen.CreateThread(function()
        while true do
            Wait(0);
            for k,func in pairs(self.ticks) do
                func();
            end
        end
    end)
end

TickManager:init();
TickManager:analayze();