---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Absolute.
--- DateTime: 24/01/2023 21:53
---

Config = {
    timeTick = 250, --- Temps entre chaque analyse de zone
    activeDebug = true,
    debugColor = {
        red = 50,
        green = 0,
        blue = 50,
        alpha = 70,
    }
}